{
 "title": "dashboard base",
 "time": { "from": "2021-01-03T00:25:00.000Z", "to": "2021-01-09T23:35:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "day",
    "label": "Day of Week",
    "query": "SELECT k AS \"__text\", v AS \"__value\" from (values ('MONDAY','MON'),('TUESDAY' ,'TUE'),('WEDNESDAY','WED'),('THURSDAY','THU'),('FRIDAY','FRI'),('SATURDAY','SAT'),('SUNDAY','SUN')) v(k,v);"
   },
   { "name": "placa_list", "label": "PLATE OF VEHICULE", "query": "select plate from test_table" },
   {
    "name": "datos",
    "label": "Real time - Prediction",
    "query": "Real : 1, Prediction : 2, All : 3"
   },
   {
    "name": "tiempo",
    "query": "select arrivaltime from test_table"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of trucks",
   "type": "stat",
   "description": "Number of trucks in this moment of visualization",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) from test_table where substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)"
    }
   ]
  },
  {
   "title": "Minimum time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"tiempo\"\nFROM test_table\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Minimum deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (abs(prediction-time)/time)*100 as \"minimum deviation\"\nFROM test_table\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maximum time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"tiempo\"\nFROM test_table\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maximum deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (abs(prediction-time)/time)*100\nFROM test_table\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"tiempo\"\nFROM test_table\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (abs(prediction-time)/time)*100 as \"average deviation\"\nFROM test_table\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Median time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY \"time\") as \"Median\"\nFROM test_table\nWHERE\n  substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Median deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY (abs(prediction-time)/time)*100) as \"median deviation\"\nFROM test_table\nWHERE\n  substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Turnaround time",
   "type": "timeseries",
   "description": "Real Time and Prediction Time, Base",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(arrivaltime,'10s', NULL),\n  plate AS metric,\n  time AS \"Real time\"\nFROM test_table\nWHERE\n  $__timeFilter(arrivaltime) AND substring(dayofweek,1,3) IN ($day) and plate in ($placa_list) and $datos = 1\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(arrivaltime,'10s', NULL),\n  plate AS metric,\n  prediction AS \"Predicted time\"\nFROM test_table\nWHERE\n  $__timeFilter(arrivaltime) AND substring(dayofweek,1,3) IN ($day) and plate in ($placa_list) and $datos = 2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(arrivaltime,'10s', NULL),\n  plate AS metric,\n  time AS \"real time\",\n  prediction AS \"predicted time\"\nFROM test_table\nWHERE\n  $__timeFilter(arrivaltime) AND substring(dayofweek,1,3) IN ($day) and plate in ($placa_list) and $datos = 3\nORDER BY 1,2,3,4"
    }
   ]
  },
  {
   "title": "Full information on selected time range",
   "type": "table",
   "description": "data of vehicles",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  plate as \"Plate\",\n  arrivaltime as \"Arrival time\",\n  departuretime as \"Departure Time\",\n  time as \"Real time\",\n  prediction as \"Prediction time\",\n  (abs(prediction-time)/time)*100 as \"Deviation\"\nFROM test_table\nwhere \n$__timeFilter(arrivaltime) AND substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Turnaround time (real time)",
   "type": "heatmap",
   "description": "Heatmap Real time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(arrivaltime,'40s', NULL),\n  plate AS metric,\n  time AS \"Real time\"\nFROM test_table\nWHERE\n  $__timeFilter(arrivaltime) AND substring(dayofweek,1,3) IN ($day) and plate in ($placa_list) and $datos in (1,3)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Number of trucks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "number of vehicles by hour" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  arrivaltime as \"time\",\n  to_char(time_short,'HH24:MM') AS metric,\n  count(id) as \"count\"\nFROM test_table\nWHERE\n  substring(dayofweek,1,3) IN ($day) and plate in ($placa_list) and $datos in (1,3)\n  group by 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}