{
 "title": "Experiments 10000",
 "time": { "from": "2021-01-01T00:00:00.000Z", "to": "2021-12-31T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "day",
    "label": "Day of Week",
    "query": "SELECT k AS \"__text\", v AS \"__value\" from (values ('MONDAY','MON'),('TUESDAY' ,'TUE'),('WEDNESDAY','WED'),('THURSDAY','THU'),('FRIDAY','FRI'),('SATURDAY','SAT'),('SUNDAY','SUN')) v(k,v);"
   },
   {
    "name": "placa_list",
    "label": "PLATE OF VEHICULE",
    "query": "select plate from test1000 union select plate from test2500 union select plate from test5000 union select plate from test10000;"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of trucks",
   "type": "stat",
   "description": "Number of trucks in this moment of visualization",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) from test10000 where substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)"
    }
   ]
  },
  {
   "title": "Minimum time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"tiempo\"\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Minimum deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (abs(prediction-time)/time)*100 as \"minimum deviation\"\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maximum time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"tiempo\"\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Maximum deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (abs(prediction-time)/time)*100\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"tiempo\"\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (abs(prediction-time)/time)*100 as \"average deviation\"\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Median time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY \"time\") as \"Median\"\nFROM test10000\nWHERE\n  substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Median deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY (abs(prediction-time)/time)*100) as \"median deviation\"\nFROM test10000\nWHERE\n  substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Table information case 10000",
   "type": "table",
   "gridPos": { "h": 24, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  plate as \"Plate\",\n  arrivaltime as \"Arrival time\",\n  departuretime as \"Departure Time\",\n  time as \"Real time\",\n  prediction as \"Prediction time\",\n  cast((abs(prediction-time)/time)*100 as numeric(20,3)) as \"Deviation\"\nFROM test10000\nwhere \nsubstring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of trucks",
   "type": "graph",
   "gridPos": { "h": 24, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "number of vehicles by hour" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  arrivaltime as \"time\",\n  to_char(time_short,'HH24:MM') AS metric,\n  count(id) as \"count\"\nFROM test10000\nWHERE\n  substring(dayofweek,1,3) IN ($day) and plate in ($placa_list)\n  group by 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}